Added feature for full screen
bryanlundberg/NexusTimer pull request #234
Opened 2023-12-29 04:05 UTC by RigvedRocks

**What does this PR do?**
I have added the functionality for the full-screen feature as outlined in #202 

**Changes**
I have added the full-screen feature to the project. In this I have made modifications to the following files and folders - 
i) Added two new files in the Icon folder for full-screen and exit full-screen icons - FullScreen.tsx and ExitFullScreen.tsx
ii) Made changes to the HeaderTimer.tsx
iii) Create a new file named fullscreenStore.tsx in the store folder.

**Screenshots or GIFs (if applicable)**
![Screenshot (101)](https://github.com/bryanlundberg/NexusTimer/assets/43703382/5e86fc3a-87fc-4190-96ca-26faad7df5a4)
![Screenshot (102)](https://github.com/bryanlundberg/NexusTimer/assets/43703382/acf32f55-a933-48ce-8186-f68156a05f5b)

**By submitting this PR, I confirm that:**
-  I have reviewed my code and believe it is ready for merging.
-  I understand that this PR may be subject to review and changes.
-  I agree to abide by the code of conduct and contributing guidelines of this project.

2023-12-29 13:42 UTC, bryanlundberg reviewed
Hi @RigvedRocks  

The overall implementation for the fullscreen logic works as I expected, but I have some issues with the UI.

Could not be merged it in its current state because you made changes in an old fork. I would suggest updating the repository before continuing your work on it.

Additionally, please switch to icons from `heroicons` and avoid committing files without any changes. Thank you.

2023-12-30 02:13 UTC, RigvedRocks commented
Thank you so much for the insights, bryanlundberg. Based on your suggestions, I have modified the code. Please have a look at the latest commit and suggest amendments if any.
![Screenshot (104)](https://github.com/bryanlundberg/NexusTimer/assets/43703382/e4bdbba3-3d1f-4ec6-a361-3239d13c5368)
![Screenshot (105)](https://github.com/bryanlundberg/NexusTimer/assets/43703382/80259ff3-d264-4e86-8935-6879f00cc429)

2023-12-30 02:50 UTC, bryanlundberg requested changes
I have to say, very nice work i like it! @RigvedRocks 

I would like to merge just the hook and icons for now. It is hard for me to determine the icon position of this feature yet.

2023-12-30 02:50 UTC, bryanlundberg commented on src/components/timer/HeaderTimer.tsx
> +        />
I'm concerned about the placement of this icon. As the repository hasn't been updated with the latest merge, this section might have an unfamiliar appearance.

2023-12-30 03:52 UTC, RigvedRocks commented on src/components/timer/HeaderTimer.tsx
> +        />
Thank you so much for the feedback. Can you shed some more light on the placement of the icon?

2023-12-30 04:22 UTC, RigvedRocks commented on src/components/timer/HeaderTimer.tsx
> +        />
Okay, I will just merge the hook and icons.

2023-12-30 04:56 UTC, RigvedRocks commented
Hey @bryanlundberg. Can you please guide me as to how I can just merge the hook and icons. I am new to the field of open-source development, I will be happy if you can help me. Sorry for the trouble.

2023-12-30 04:58 UTC, RigvedRocks commented
@bryanlundberg Can you please guide me as to how I can just merge the hooks and icons. I am new to the field of open-source development. Sorry for the trouble. If you want to I can close this draft PR, and open a new one with the hooks and icons.

2023-12-30 13:26 UTC, bryanlundberg reviewed
If you prefer, you can simply create a new pull request with the hook and icons, it might make things easier. 😅

Additionally, I have some other ideas about where to position the fullscreen button.

2023-12-30 13:26 UTC, bryanlundberg commented on src/components/timer/HeaderTimer.tsx
>    if (isSolving || timerStatus !== "IDLE") return null;
This is not correctly merged

2023-12-30 18:27 UTC, RigvedRocks commented on src/components/timer/HeaderTimer.tsx
>    if (isSolving || timerStatus !== "IDLE") return null;
Okay, I will see to it, thank for pointing it out

2023-12-30 18:33 UTC, closed without merging

2023-12-30 18:34 UTC, RigvedRocks commented
Closing this draft PR and opening a new one, merging the hook and icons along with changes to the timer component.