disabled buttons when cube is not selected
bryanlundberg/NexusTimer pull request #237
Opened 2023-12-29 17:59 UTC by Ganesh107

**What does this PR do?**
I have addressed the issue #222 

**Changes**
Disabled the button when no cube is selected from the select list in the solves page.

**Screenshots or GIFs (if applicable)**
If your PR includes visual changes, provide screenshots or GIFs to demonstrate the ![btn_fix](https://github.com/bryanlundberg/NexusTimer/assets/78807238/6e6141dd-76f0-4499-8acd-6cf4123c3fcb).

**By submitting this PR, I confirm that:**
- [x] I have reviewed my code and believe it is ready for merging.
- [x] I understand that this PR may be subject to review and changes.
- [x] I agree to abide by the code of conduct and contributing guidelines of this project.

2023-12-29 19:05 UTC, bryanlundberg requested changes
Appreciate your effort on the PR! Just a few minor adjustments in the comments to enhance. Thanks!

@Ganesh107

2023-12-30 05:21 UTC, Ganesh107 commented on src/hooks/useSolvesPage.ts
> +    selectedCube
ok I'll work on it

2023-12-30 05:22 UTC, Ganesh107 commented on src/hooks/useSolvesPage.ts
> +    selectedCube
ok I'll work on it

2023-12-30 05:26 UTC, Ganesh107 commented on src/hooks/useSolvesPage.ts
> +    selectedCube
ok I'll work on it

2023-12-30 07:35 UTC, Ganesh107 commented on src/components/button/ButtonContainer.tsx
> +        onClick={!isDisabled ? handleClick : undefined}
onClick?: MouseEventHandler<T> | undefined; onclick can only take these values as defined in index.d.ts file so i will have to make changes in index.d.ts file if i have to use null instead of undefined

2023-12-30 11:31 UTC, bryanlundberg commented on src/components/button/ButtonContainer.tsx
> +        onClick={!isDisabled ? handleClick : undefined}
Ok let it be undefined

2023-12-30 13:12 UTC, bryanlundberg commented on src/components/button/ButtonContainer.tsx
> +        onClick={!isDisabled ? handleClick : undefined}
I just remembered that disabled buttons won't trigger the click event. 😅

You can still use `onClick={handleClick}`

2023-12-30 13:14 UTC, bryanlundberg approved these changes
thank you for your contribution!

2023-12-30 13:14 UTC, merged