added a sort solves feature
bryanlundberg/NexusTimer pull request #326
Opened 2024-07-08 13:50 UTC by syrok94

**What does this PR do?**
feat #286 

**Related Issue(s)**
there is an issue in the added sort button on the page.tsx 
- button has label of move-all
- -need help to fix that out

@bryanlundberg I have added the feature. Please review this and let me know the changes .

**By submitting this PR, I confirm that:**
- [x] I have reviewed my code and believe it is ready for merging.
- [x] I understand that this PR may be subject to review and changes.
- [x] I agree to abide by the code of conduct and contributing guidelines of this project.

2024-07-08 21:12 UTC, bryanlundberg requested changes
Hey  @syrok94  it sorts as expected 😅

But the UI is not well implemented.

![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/4dec75c0-6168-4c28-9ab0-ce8f69498432)


I think design could look a lot better like this:
![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/b2ed6f70-af5e-41b0-bea0-1ddec65fdf6d)


![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/86bb63b5-7c74-4d8f-ab42-dfcf85c9100c)

Design complexity has increased. 😁

2024-07-09 05:01 UTC, syrok94 commented
Okay, I will change the UI.

2024-07-09 09:34 UTC, bryanlundberg commented
We can maintain it as a third row and add all other sorting +2, comments, favorites, etc. But let's begin with the date and time. 👌

2024-07-09 11:13 UTC, syrok94 commented
hey @bryanlundberg I have changed the UI...please check once.
![ss](https://github.com/bryanlundberg/NexusTimer/assets/58144335/0ecd08a5-edaa-48aa-86b1-645a0fc75804)
you see, On my laptop width of the screen is full..I think that is why My UI gets wrong all the time

2024-07-09 15:27 UTC, bryanlundberg requested changes
Hey @syrok94 , I checked more in depth and have some requests for changes to optimize the implementation.

About buttons order would fit better, change the order
![image](https://github.com/bryanlundberg/NexusTimer/assets/119996547/c21785c4-9bfb-4e86-90f9-36385e95ef89)

In this case, menu sorting, can be placed `absolute top-0 right-0`

Thanks!

2024-07-09 15:27 UTC, bryanlundberg commented on src/app/[locale]/solves/page.tsx
> +      )}
The placement of this section here is causing the menu to be incorrectly positioned there's no relative point. This is what we were discussing, but you cant see it because of the screen size. 🫡

2024-07-09 15:27 UTC, bryanlundberg commented on src/app/[locale]/solves/page.tsx
> +  const sortedSolves = displaySolves ? [...displaySolves] : [];
A boolean useState is not necessary to chain multiple states until force a render. The solved array is saved in a state `displaySolves`, and if you change it, it will automatically trigger a new render.

2024-07-09 15:27 UTC, bryanlundberg commented on src/app/[locale]/solves/page.tsx
> +              </div>
Inside this div, should go the menu, so it positions based on relative point.


```
                {sortModal && (
                  <div className="absolute right-0">
                    <SortMenu
                      setSortModal={setSortModal}
                      submenuRef={submenuRef}
                      setIsSorted={setIsSorted}
                      setSortType={setSortType}
                    />
                  </div>
                )}
```

2024-07-09 15:27 UTC, bryanlundberg commented on src/app/[locale]/solves/page.tsx
> +          displaySolves={isSorted ? sortedSolves : displaySolves}
Somehow, perform the sort before reaching this point and finish as expected: `displaySolves={displaySolves}`

2024-07-11 01:52 UTC, bryanlundberg commented
- add animation open/close
- add translations to options
- simplified usage of states

now looks ready to publish, thanks @syrok94 !

2024-07-11 01:53 UTC, merged