added a share solves options dropdown
bryanlundberg/NexusTimer pull request #329
Opened 2024-07-13 18:58 UTC by syrok94

**What does this PR do?**
feat #324 

**Related Issue(s)**
none

**Screenshots or GIFs (if applicable)**
![a](https://github.com/user-attachments/assets/1f86a6e8-512d-4c23-a8cf-7cf8a5aca3b4)
![b](https://github.com/user-attachments/assets/24a6a56f-6bcd-4a52-a1c7-c68bdbd0c194)

**Additional Comments**
hii @bryanlundberg , please review and suggest if some optimization can be made

**By submitting this PR, I confirm that:**
- [x] I have reviewed my code and believe it is ready for merging.
- [x] I understand that this PR may be subject to review and changes.
- [x] I agree to abide by the code of conduct and contributing guidelines of this project.

2024-07-14 00:18 UTC, bryanlundberg requested changes
I believe your initial intention was to keep the first menu open, and the second menu opens on top of the previous menu.

However, it's a bit strange because the animations are activated, and in the background, I can see the previous menu. It doesn't give the impression of being the same.

2024-07-14 00:18 UTC, bryanlundberg commented on src/components/solves/ShareMenu.tsx
> +  };
It's not required to include a comma (",") after each

2024-07-14 14:11 UTC, syrok94 commented
hii @bryanlundberg  I have made changes and please let me know more info regarding the previous menu in the background.

2024-07-14 14:25 UTC, bryanlundberg commented
I like the latest changes; let's keep that design.👌

Regarding the clipboard result, it's important to keep it compact without empty rows.

![image](https://github.com/user-attachments/assets/03dbc45f-5b9e-43a2-96af-7f786db63702)

Also, please ensure that the left side remains aligned.

![image](https://github.com/user-attachments/assets/61e9cbce-5e03-46cc-beb6-7aae118bc2c4)

2024-07-15 04:09 UTC, syrok94 commented
Hi @bryanlundberg, Fix the changes, please review.

2024-07-15 11:22 UTC, bryanlundberg commented
You are doing great, but I have a few minor suggestions 😬

Last changes:

- "Generated by NexusTimer" is missing internalization.
- There should not be a space before the colon (":").

Additionally, this was not request at start but I think it helps improve the visual layout. If you could numerate the solves like this:

1. [time]: [scramble]
2. [time]: [scramble]
3. [time]: [scramble]
... 


Please, @syrok94 😅

2024-07-15 12:30 UTC, syrok94 commented
@bryanlundberg Fixed it.
> Generated by NexusTimer: 7/15/2024 
> Average 5: 0.67 
>
>List of times: 
>
>   1. (2.04) F  U2 R  U2 R  U  R2 
>   2. 0.62 U' R2 U2 F  U' F' U  R2 
>   3. (0.50) U' F2 R2 U' R  U' F' R2 
>   4. 0.54 U' R  U  F' U  R' U  R' U' 
>   5. 0.84 U2 R' F' R2 U  F' R' F  U2

2024-07-15 13:14 UTC, bryanlundberg commented
> @bryanlundberg Fixed the changes and I want to know that you want to Internationalize the "Generated by NexusTimer" , "Average" and "List of times" ?
> 
> > Generated by NexusTimer: 7/15/2024
> > Average 5: 0.67
> > List of times:
> > 
> > 1. (2.04) F  U2 R  U2 R  U  R2
> > 2. 0.62 U' R2 U2 F  U' F' U  R2
> > 3. (0.50) U' F2 R2 U' R  U' F' R2
> > 4. 0.54 U' R  U  F' U  R' U  R' U'
> > 5. 0.84 U2 R' F' R2 U  F' R' F  U2

That's correct, let's internalize everything!

2024-07-15 13:27 UTC, syrok94 commented
@bryanlundberg fixed it

2024-07-16 10:20 UTC, bryanlundberg commented
Feature ready!
Thank you again @syrok94 👌

2024-07-16 10:21 UTC, merged