Updated styling in ImportModal.tsx
bryanlundberg/NexusTimer pull request #384
Opened 2024-11-09 09:23 UTC by arashveysi3

fixed a styling problem that keeps happening when you click on 'settings/import from file' in light mode. stylings changed to drop blur instead of white and black with an opacity of %10

**What does this PR do?**
The import screen dialog background is now blurry

**Related Issue(s)**
Issue #383 

**Screenshots or GIFs (if applicable)**
Light Mode:

![image](https://github.com/user-attachments/assets/d950b166-9cab-41c6-84e3-5c5785adb9d4)

Dark Mode:

![Screenshot (6)](https://github.com/user-attachments/assets/0fe2ac4e-4b65-48e2-8525-1d5df29a3583)

2024-11-09 09:39 UTC, arashveysi3 commented
It seems I don’t have authorization for deployment checks. please let me know if there’s anything else I should address.

2024-11-09 12:36 UTC, bryanlundberg commented
Hi, @arashveysi3 thanks for your interest, today I was going to refactor that modal with a custom dialog from shadcn, that's why I didn't describe it too much 🫡. Because that one continue having the styles from old UI, I just forgot migrate that component.

Anyway, about your implementation, I prefer a dark background instead of a blur. Require a little bit of borders. Also, there is a wrong synchronization showing the blur effect and the modal. Like a delay. Feels strange as user experience.

I'm open to let you refactor that component using shadcn/dialog. ¿Do you want to continue?😅

2024-11-09 13:07 UTC, arashveysi3 commented
Hey! 
Thanks for reviewing my PR. 
And YES. I am open to any contributions that might help. 
Count on me 🙂

2024-11-09 14:06 UTC, bryanlundberg commented
> Hey @bryanlundberg  
> Thanks for reviewing my PR. 
> And YES. I am open to any contributions that might help. 
> Count on me 🙂 

Great

2024-11-09 19:39 UTC, arashveysi3 commented
> > Hey @bryanlundberg
> > Thanks for reviewing my PR.
> > And YES. I am open to any contributions that might help.
> > Count on me 🙂
> 
> Great

refactored to Shadcn/ui. please take a look.
hope it helps...

2024-11-10 10:58 UTC, bryanlundberg requested changes
Hey @arashveysi3 it's a good improvement, but there are some minor changes before merge. Just to help keep the general components flow


1. the trigger of the modals should be placed in the spot of the button.

That means I need you to change the 

components/menu-settings/DataImportExport.tsx
```
<Dialog>
  <DialogTrigger>Open</DialogTrigger>
  <DialogContentMadeByYou />
</Dialog>
```

2. Your custom dialog for import
```
  <DialogContent>
    <DialogHeader>
      <DialogTitle></DialogTitle>
      <DialogDescription></DialogDescription>
    ....
    </DialogHeader>
  </DialogContent>
```

3. Clean the global state of the previous modal "importModalOpen: boolean" and its function to change. Are not necessary anymore.

store/settingsModalStore.ts

4. Delete the usage of actual `<ImportModal />` app/settings/options/page.tsx line: 129`

I think that's it 👌

2024-11-10 10:58 UTC, bryanlundberg commented on src/components/menu-settings/ImportModal.tsx
> +          <Dialog open={importModalOpen} onOpenChange={setImportModalOpen}>
`{importModalOpen && (` become redundant with `<Dialog open={importModalOpen}`

2024-11-10 10:58 UTC, bryanlundberg commented on src/components/menu-settings/ImportModal.tsx
>          {importModalOpen && (
Makes the fade-out animation from shadcn not be displayed as component disappear from DOM.

2024-11-10 10:58 UTC, bryanlundberg commented on src/components/menu-settings/ImportModal.tsx
>    useClickOutside(componentRef, () => setImportModalOpen(false));
This can be removed. Not used anymore.

2024-11-10 12:02 UTC, arashveysi3 commented on src/components/menu-settings/ImportModal.tsx
>    useClickOutside(componentRef, () => setImportModalOpen(false));
Hey! just committed the new improvements. please take a look and let me know if further improvements needed..

2024-11-12 10:51 UTC, merged